### PR TITLE
Add basic fixture declaration

### PR DESCRIPTION
**Pull request by subsetpark**
This is completely unsolicited and I didn't check in with you beforehand about the desirability of this feature, so totally understood if a) you don't want to add it or b) you don't like the API. But I figured i'd give it a whack and see how it turned out.

### CODE REVIEW

**Comment by subsetpark** [comment]
One thing to consider is, ultimately, you'd want to be able to declare other important callbacks for tests:

- setups to be run once-per-group (or module), not just once per test
- teardowns
- teardowns once-per-group.

The (or module) suggests that you might not need any dedicated API for that part; you could just call your setup and teardown directly in the top level.

The per-case teardown, of course, would presumably need more of an API. So that would presumably impact the design decision here as well. The most naive way would be to wrap a `with-fixtures` call in a `with-teardowns` call, but that's pretty obviously awful. You could make it an optional second argument to `with-fixtures`. Or, you could specify a richer API altogether. For instance, something like:

```
(describe
  (fixtures [fn1 fn2 fn3])
  (teardown [fn4])
  (deftest ...)
  (deftest ...))
```

**Comment by pyrmont** [comment]
@subsetpark I often looked to the way Clojure's [clojure.test](https://clojure.github.io/clojure/clojure.test-api.html) library did things when I created the original Testament API. What do you think about their approach to fixtures?

**Comment by subsetpark** [comment]
Makes sense to me!

**Comment by subsetpark** [comment]
I'll take a swing at this today. I don't want to follow the clojure example too slavishly, since we don't have namespaces. So an effectful "use fixtures" command would make it difficult to specify different fixtures for different tests. I'll play around a little bit with how to invoke them, but fixture-as-decorator works for me.

**Comment by pyrmont** [comment]
I was looking at this again as well and I agree with you that clojure.test's `use-fixtures` approach doesn't feel like a Janet-y solution given its relationship to namespaces.

> One thing to consider is, ultimately, you'd want to be able to declare other important callbacks for tests:
> 
> * setups to be run once-per-group (or module), not just once per test
> * teardowns
> * teardowns once-per-group.
> 
> The (or module) suggests that you might not need any dedicated API for that part; you could just call your setup and teardown directly in the top level.

So I was thinking about this and I wonder if we want the macro to be named differently. The `with-` macros in core are all about creating a temporary environment where bindings have the values set in the initial tuple. I don't think that's really what we want to do here. We do want to create a temporary environment but we want more control over how that temporary environment is constructed and destroyed.

For that scenario, what do you think about using `in-` rather than `with-`? So, for example, you could have `in-env` or `in-environment`. Personally, my preference would be `in-context` since `env` is used in other places in Janet and I'd be worried people might misunderstand how this is intended to be used.

The semantics of `in-context` could work like this (my macro-fu is terrible so I this is merely for illustrative purposes):

```janet
(defmacro in-context
  "Run body in a context created by the function associated with the `:setup` key
  in `setups-and-teardowns` and destroyed by the function associated with the
  `:teardown` key." 
  [setups-and-teardowns & body]
  (def setups (setups-and-teardowns :setup))
  (def teardowns (setups-and-teardowns :teardown))
  ~((,setup)
    (do ;,body)
    (,teardown))
```

**Pull request closed without merging**
